# Generated by Django 5.0 on 2024-01-10 16:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('self_ticket', 'Self Ticket'), ('point_of_sale', 'Point of Sale'), ('unknown', 'Unknown')], max_length=20)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('postcode', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\d+\\.\\d{2}$')])),
                ('currency', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(regex='^[A-Z]{3}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('doors', models.TimeField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webhook.location')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('online_presale', 'Online Presale'), ('ticket_proof', 'Ticket Proof'), ('self_ticket', 'Self Ticket')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('event', models.CharField(max_length=200)),
                ('eventId', models.IntegerField()),
                ('cancellationReason', models.CharField(blank=True, choices=[('', 'None'), ('undef_cancellation', 'Undefined Cancellation'), ('order_mistake', 'Order Mistake'), ('event_cancellation', 'Event Cancellation'), ('event_postponed', 'Event Postponed'), ('stolen', 'Stolen'), ('test_ticket', 'Test Ticket'), ('selfticket_mistake', 'Selfticket Mistake')], default='', max_length=50)),
                ('promoter', models.CharField(max_length=200)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webhook.price')),
                ('sessions', models.ManyToManyField(to='webhook.session')),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('ticket_created', 'Ticket Created'), ('ticket_updated', 'Ticket Updated')], max_length=20)),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webhook.buyer')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webhook.ticket')),
            ],
        ),
    ]
